"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create date: ${create_date}

Before opening a PR, fill in what a reviewer cannot see from the SQL:

  Why:          what this migration is for
  Data impact:  rows rewritten, locks taken, how long it runs on a realistic table
  Downgrade:    safe, or lossy and therefore forward-fix only (say which, and why)

Autogenerated migrations are a draft. Read every statement: Alembic cannot tell a rename from a
drop-plus-add, and getting that wrong loses data.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
