#!/usr/bin/env python
"""Generate .github/CODEOWNERS from ops/discord/config.yaml.

Rules (GitHub: the LAST matching pattern wins, so shared/critical files go last):
  1. everything            -> lead
  2. each workstream folder -> its owner(s)  (module 06 folders get riskmodel + rag)
  3. shared surfaces        -> lead + affected owners (contracts, compose, CI, Dockerfiles)

Workstreams whose `github:` is still null are written as commented TODO lines so
GitHub does not silently ignore a bad username. Check names with `gh api users/<name>`.

Usage: python gen_github.py [--check]
"""
from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"


def handle(user: str | None) -> str | None:
    return f"@{user.lstrip('@')}" if user else None


def render(cfg: dict) -> str:
    lead = handle(cfg["lead_role"].get("github"))
    lead_txt = lead or "@<LEAD-GITHUB-USERNAME>"
    lines = [
        "# Generated by ops/discord/gen_github.py from ops/discord/config.yaml - edit the config, not this file.",
        "# Last matching pattern wins. Owners are auto-requested for review on every PR touching their paths.",
        "",
        "# 1) default: lead owns everything not listed below",
        f"{'*':<44} {lead_txt}",
        "",
        "# 2) workstream folders",
    ]
    # folder -> ordered set of owners (module 06 has two workstreams on the same folder)
    folder_owners: "OrderedDict[str, list[str | None]]" = OrderedDict()
    for ws in cfg["workstreams"]:
        owner = handle(ws.get("github"))
        for f in ws["folders"]:
            pattern = "/" + f if not f.startswith("/") else f
            folder_owners.setdefault(pattern, [])
            if owner and owner not in folder_owners[pattern]:
                folder_owners[pattern].append(owner)
            elif not owner:
                folder_owners[pattern].append(None)
    shared_prefixes = ("/packages/contracts", "/infra/", "/ops/", "/.github/", "/compose", "/.env.example", "/Makefile")
    for pattern, owners in folder_owners.items():
        real = [o for o in owners if o]
        todo = any(o is None for o in owners)
        is_shared = pattern.startswith(shared_prefixes)
        owner_txt = " ".join(real + ([lead] if is_shared and lead and lead not in real else []))
        line = f"{pattern:<44} {owner_txt}".rstrip()
        if todo or not real:
            lines.append(f"# TODO set github: in config.yaml -> {line}")
        else:
            lines.append(line)
    lines += ["", "# 3) shared surfaces (must stay last): lead reviews all of these, plus the affected owner"]
    for pattern in ["/packages/contracts/", "/compose.yaml", "/compose.dev.yaml", "/.env.example", "/.github/",
                    "/IMPLEMENTATION_PLANS/", "/services/*/Dockerfile", "/apps/*/Dockerfile",
                    "/IMPLEMENTATION_PLANS/00_API_AND_DATA_CONTRACTS.md"]:
        extra = [o for o in folder_owners.get(pattern, []) if o and o != lead]
        lines.append(f"{pattern:<44} {' '.join([lead_txt] + extra)}")
    lines.append("")
    return "\n".join(lines)


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if CODEOWNERS is out of date")
    ap.add_argument("--config", default=str(HERE / "config.yaml"))
    a = ap.parse_args()
    cfg = yaml.safe_load(Path(a.config).read_text(encoding="utf-8"))
    text = render(cfg)
    if a.check:
        cur = CODEOWNERS.read_text(encoding="utf-8") if CODEOWNERS.exists() else ""
        if cur != text:
            print("CODEOWNERS is out of date - run: python ops/discord/gen_github.py")
            sys.exit(1)
        print("CODEOWNERS up to date")
        return
    CODEOWNERS.parent.mkdir(parents=True, exist_ok=True)
    CODEOWNERS.write_text(text, encoding="utf-8")
    missing = [ws["key"] for ws in cfg["workstreams"] if not ws.get("github")]
    if not cfg["lead_role"].get("github"):
        missing.insert(0, "lead")
    print(f"wrote {CODEOWNERS.relative_to(ROOT)}")
    if missing:
        print(f"TODO: set github: in config.yaml for {', '.join(missing)} then re-run")


if __name__ == "__main__":
    main()
