"""OpenAPI snapshot and contract verification for Public API.

Ensures that FastAPI's auto-generated OpenAPI schema:
1. Exactly matches the committed snapshot in `tests/snapshots/openapi_snapshot.json`.
2. Fully implements all routes, operations, and HTTP methods declared in contract
   `packages/contracts/openapi/public-api.yaml`.
3. Adheres to contract metadata, tags, and security scheme specifications.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pytest
import yaml

from app.main import create_app
from tests.conftest import build_settings


def _find_contracts_dir() -> Path:
    configured = os.environ.get("CONTRACTS_DIR")
    if configured:
        return Path(configured)

    for ancestor in Path(__file__).resolve().parents:
        candidate = ancestor / "packages" / "contracts"
        if candidate.is_dir():
            return candidate
    return Path("packages/contracts")


CONTRACTS_DIR = _find_contracts_dir()
PUBLIC_API_SPEC_PATH = CONTRACTS_DIR / "openapi" / "public-api.yaml"
SNAPSHOT_PATH = Path(__file__).resolve().parent / "snapshots" / "openapi_snapshot.json"


@pytest.fixture(scope="module")
def generated_openapi() -> dict[str, Any]:
    app = create_app(build_settings())
    return app.openapi()


@pytest.fixture(scope="module")
def public_api_spec() -> dict[str, Any]:
    if not PUBLIC_API_SPEC_PATH.exists():
        pytest.skip(f"Contract file not found at {PUBLIC_API_SPEC_PATH}")
    return yaml.safe_load(PUBLIC_API_SPEC_PATH.read_text(encoding="utf-8"))


def test_openapi_snapshot_matches_generated_schema(generated_openapi: dict[str, Any]) -> None:
    """The OpenAPI spec generated by FastAPI must match the frozen snapshot."""
    assert SNAPSHOT_PATH.exists(), f"Missing OpenAPI snapshot file at {SNAPSHOT_PATH}"
    snapshot = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))

    # Compare paths count and path keys
    assert set(generated_openapi["paths"].keys()) == set(snapshot["paths"].keys()), (
        f"Paths mismatch! Extra: {set(generated_openapi['paths']) - set(snapshot['paths'])}, "
        f"Missing: {set(snapshot['paths']) - set(generated_openapi['paths'])}"
    )

    # Compare full serialized json equality
    generated_json = json.dumps(generated_openapi, indent=2, sort_keys=True, ensure_ascii=False)
    snapshot_json = json.dumps(snapshot, indent=2, sort_keys=True, ensure_ascii=False)
    assert generated_json == snapshot_json, (
        "Generated OpenAPI schema drifted from committed snapshot. "
        "If changes were intentional, update tests/snapshots/openapi_snapshot.json"
    )


def test_all_contract_paths_and_methods_implemented(
    generated_openapi: dict[str, Any], public_api_spec: dict[str, Any]
) -> None:
    """Every path and method defined in public-api.yaml must be present in the generated spec."""
    contract_paths = public_api_spec.get("paths", {})
    impl_paths = generated_openapi.get("paths", {})

    http_methods = {"get", "post", "put", "patch", "delete", "options", "head"}

    missing_operations: list[str] = []
    for path, path_item in contract_paths.items():
        if path not in impl_paths:
            missing_operations.append(f"Missing entire path: {path}")
            continue

        for method, _operation in path_item.items():
            if method.lower() not in http_methods:
                continue
            if method.lower() not in impl_paths[path]:
                missing_operations.append(f"Missing {method.upper()} on path {path}")

    assert (
        not missing_operations
    ), f"Contract operations missing in implementation: {missing_operations}"


def test_contract_security_schemes_and_tags(
    generated_openapi: dict[str, Any], public_api_spec: dict[str, Any]
) -> None:
    """Validate security schemes and general metadata."""
    assert "paths" in generated_openapi
    assert len(generated_openapi["paths"]) >= 21

    # Security schemes in components
    components = generated_openapi.get("components", {})
    security_schemes = components.get("securitySchemes", {})
    has_security = (
        "OAuth2PasswordBearer" in security_schemes
        or "bearerAuth" in security_schemes
        or len(security_schemes) > 0
    )
    assert has_security

    # Ensure all implemented endpoints have operation summaries or responses
    for path, methods in generated_openapi["paths"].items():
        for method, op_data in methods.items():
            if method in {"get", "post", "put", "patch", "delete"}:
                assert "responses" in op_data, f"Endpoint {method.upper()} {path} missing responses"
